Update workflow file to delete other files

diff --git a/.github/workflows/prod-frontend-google-cdn.yml b/.github/workflows/prod-frontend-google-cdn.yml
--- a/.github/workflows/prod-frontend-google-cdn.yml
+++ b/.github/workflows/prod-frontend-google-cdn.yml
@@ -31,6 +31,9 @@ jobs:
         with:
           credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
 
+      - name: "Set up Cloud SDK"
+        uses: "google-github-actions/setup-gcloud@v0"
+
       - name: Build Frontend
         shell: bash
         run: |-
@@ -38,17 +41,8 @@ jobs:
           npm install
           npm run build
 
-      - name: Clear Bucket
-        run: gsutil -m rm -r gs://${{ secrets.PROD_SITE_BUCKET_NAME }}/*
+      - name: "Validate directory not empty"
+        run: '[ "$(ls -A frontend/dist)" ] && echo "Files exist - all good." || (echo "Directory is empty - aborting." && exit 1)'
 
-      - id: "upload-files"
-        name: Upload Files to GCP
-        uses: "google-github-actions/upload-cloud-storage@v1"
-        with:
-          path: "frontend/dist/**"
-          destination: "${{ env.BUCKET }}"
-          parent: false
-          gzip: true
-          resumable: true
-          concurrency: 100
-          process_gcloudignore: true
+      - name: "Upload Site"
+        run: "gsutil -m rsync -R -d frontend/dist gs://${{ env.BUCKET }}"
